// Shared corpus fixture for the docs-index and query-docs tests. It must stay in sync
// with the alignment it exercises: the two TOC entries match the two pages in order, so
// a page whose TOC entry is missing (see the unlisted-page test) is the only way to get
// a chunk without a path.
export const DOCS_FIXTURE = [
  '# WebdriverIO Docs',
  '',
  '- [waitUntil](/docs/api/browser/waitUntil.md)',
  '- [Usage](/docs/usage.md)',
  '',
  '---',
  '',
  '# Full Documentation Content',
  '',
  '# waitUntil',
  '',
  'Waits until a condition returns true.',
  '',
  '```js',
  '# Not a page heading',
  "browser.waitUntil(() => $('#foo').isDisplayed(), { timeout: 5000 })",
  '```',
  '',
  '## Parameters',
  '',
  '| name | type |',
  '| --- | --- |',
  '| condition | `Function` |',
  '',
  '```',
  'raw block',
  '``` |',
  '',
  '# Usage',
  '',
  'Second page body mentions waitUntil too.',
  '',
  '## Options',
  '',
  'timeout in milliseconds',
  '',
].join('\n');